namespace rec PlatformApi.Types

type ChannelDetails =
    { ///The required name of the channel including any qualifier, if any.
      channelId: string
      ///In events relating to the activity of a channel in a specific region, this optionally identifies whether or not that region is responsible for global coordination of the channel.
      isGlobalMaster: Option<bool>
      ///In events relating to the activity of a channel in a specific region, this optionally identifies the region.
      region: Option<string>
      ///A ChannelStatus instance.
      status: Option<ChannelStatus> }
    ///Creates an instance of ChannelDetails with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (channelId: string): ChannelDetails =
        { channelId = channelId
          isGlobalMaster = None
          region = None
          status = None }

///A ChannelStatus instance.
type ChannelStatus =
    { ///A required boolean value indicating whether the channel that is the subject of the event is active. For events indicating regional activity of a channel this indicates activity in that region, not global activity.
      isActive: bool
      ///An Occupancy instance indicating the occupancy of a channel. For events indicating regional activity of a channel this indicates activity in that region, not global activity.
      occupancy: Option<Occupancy> }
    ///Creates an instance of ChannelStatus with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (isActive: bool): ChannelStatus =
        { isActive = isActive
          occupancy = None }

[<Fable.Core.StringEnum; RequireQualifiedAccess>]
type FormFactor =
    | [<CompiledName "phone">] Phone
    | [<CompiledName "tablet">] Tablet
    | [<CompiledName "desktop">] Desktop
    | [<CompiledName "tv">] Tv
    | [<CompiledName "watch">] Watch
    | [<CompiledName "car">] Car
    | [<CompiledName "embedded">] Embedded
    member this.Format() =
        match this with
        | Phone -> "phone"
        | Tablet -> "tablet"
        | Desktop -> "desktop"
        | Tv -> "tv"
        | Watch -> "watch"
        | Car -> "car"
        | Embedded -> "embedded"

[<Fable.Core.StringEnum; RequireQualifiedAccess>]
type Platform =
    | [<CompiledName "ios">] Ios
    | [<CompiledName "android">] Android
    member this.Format() =
        match this with
        | Ios -> "ios"
        | Android -> "android"

[<Fable.Core.StringEnum; RequireQualifiedAccess>]
type Pushstate =
    | [<CompiledName "Active">] Active
    | [<CompiledName "Failing">] Failing
    | [<CompiledName "Failed">] Failed
    member this.Format() =
        match this with
        | Active -> "Active"
        | Failing -> "Failing"
        | Failed -> "Failed"

type DeviceDetails =
    { ///Optional trusted client identifier for the device.
      clientId: Option<string>
      ///Secret value for the device.
      deviceSecret: Option<string>
      ///Form factor of the push device.
      formFactor: Option<FormFactor>
      ///Unique identifier for the device generated by the device itself.
      id: Option<string>
      ///Optional metadata object for this device. The metadata for a device may only be set by clients with push-admin privileges and will be used more extensively in the future with smart notifications.
      metadata: Option<Newtonsoft.Json.Linq.JObject>
      ///Platform of the push device.
      platform: Option<Platform>
      ///Push recipient details for a device.
      ``push.recipient``: Option<Recipient>
      ///the current state of the push device.
      ``push.state``: Option<Pushstate> }

///Returned error from failed REST.
type Error =
    { ///Error code.
      code: Option<int>
      ///Link to help with error.
      href: Option<string>
      ///Message explaining the error's cause.
      message: Option<string>
      ///Server ID with which error was encountered.
      serverId: Option<string>
      ///Status error code.
      statusCode: Option<int> }
    ///Creates an instance of Error with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (): Error =
        { code = None
          href = None
          message = None
          serverId = None
          statusCode = None }

///Extras object. Currently only allows for [push](https://www.ably.io/documentation/general/push/publish#channel-broadcast-example) extra.
type Extras =
    { push: Option<Push> }
    ///Creates an instance of Extras with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (): Extras = { push = None }

///Message object.
type Message =
    { ///The [client ID](https://www.ably.io/documentation/core-features/authentication#identified-clients) of the publisher of this message.
      clientId: Option<string>
      ///The connection ID of the publisher of this message.
      connectionId: Option<string>
      ///The string encoded payload, with the encoding specified below.
      data: Option<string>
      ///This will typically be empty as all messages received from Ably are automatically decoded client-side using this value. However, if the message encoding cannot be processed, this attribute will contain the remaining transformations not applied to the data payload.
      encoding: Option<string>
      ///Extras object. Currently only allows for [push](https://www.ably.io/documentation/general/push/publish#channel-broadcast-example) extra.
      extras: Option<Extras>
      ///A Unique ID that can be specified by the publisher for [idempotent publishing](https://www.ably.io/documentation/rest/messages#idempotent).
      id: Option<string>
      ///The event name, if provided.
      name: Option<string>
      ///Timestamp when the message was received by the Ably, as milliseconds since the epoch.
      timestamp: Option<int64> }
    ///Creates an instance of Message with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (): Message =
        { clientId = None
          connectionId = None
          data = None
          encoding = None
          extras = None
          id = None
          name = None
          timestamp = None }

type Notification =
    { ///Text below title on the expanded notification.
      body: Option<string>
      ///Platform-specific, used to group notifications together.
      collapseKey: Option<string>
      ///Platform-specific icon for the notification.
      icon: Option<string>
      ///Platform-specific sound for the notification.
      sound: Option<string>
      ///Title to display at the notification.
      title: Option<string> }
    ///Creates an instance of Notification with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (): Notification =
        { body = None
          collapseKey = None
          icon = None
          sound = None
          title = None }

///An Occupancy instance indicating the occupancy of a channel. For events indicating regional activity of a channel this indicates activity in that region, not global activity.
type Occupancy =
    { ///The number of connections that are authorised to enter members into the presence channel.
      presenceConnections: Option<int>
      ///The number of members currently entered into the presence channel.
      presenceMembers: Option<int>
      ///The number of connections that are authorised to subscribe to presence messages.
      presenceSubscribers: Option<int>
      ///The number of connections attached to the channel that are authorised to publish.
      publishers: Option<int>
      ///The number of connections attached that are authorised to subscribe to messages.
      subscribers: Option<int> }
    ///Creates an instance of Occupancy with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (): Occupancy =
        { presenceConnections = None
          presenceMembers = None
          presenceSubscribers = None
          publishers = None
          subscribers = None }

[<Fable.Core.StringEnum; RequireQualifiedAccess>]
type Action =
    | [<CompiledName "ABSENT">] ABSENT
    | [<CompiledName "PRESENT">] PRESENT
    | [<CompiledName "ENTER">] ENTER
    | [<CompiledName "LEAVE">] LEAVE
    | [<CompiledName "UPDATE">] UPDATE
    member this.Format() =
        match this with
        | ABSENT -> "ABSENT"
        | PRESENT -> "PRESENT"
        | ENTER -> "ENTER"
        | LEAVE -> "LEAVE"
        | UPDATE -> "UPDATE"

type PresenceMessage =
    { ///The event signified by a PresenceMessage.
      action: Option<Action>
      ///The client ID of the publisher of this presence update.
      clientId: Option<string>
      ///The connection ID of the publisher of this presence update.
      connectionId: Option<string>
      ///The presence update payload, if provided.
      data: Option<string>
      ///This will typically be empty as all presence updates received from Ably are automatically decoded client-side using this value. However, if the message encoding cannot be processed, this attribute will contain the remaining transformations not applied to the data payload.
      encoding: Option<string>
      ///Extras object. Currently only allows for [push](https://www.ably.io/documentation/general/push/publish#channel-broadcast-example) extra.
      extras: Option<Extras>
      ///Unique ID assigned by Ably to this presence update.
      id: Option<string>
      ///Timestamp when the presence update was received by Ably, as milliseconds since the epoch.
      timestamp: Option<int64> }
    ///Creates an instance of PresenceMessage with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (): PresenceMessage =
        { action = None
          clientId = None
          connectionId = None
          data = None
          encoding = None
          extras = None
          id = None
          timestamp = None }

///Extends and overrides generic values when delivering via APNs. [See examples](https://www.ably.io/documentation/general/push/publish#payload-structure)
type Apns =
    { notification: Option<Notification> }
    ///Creates an instance of Apns with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (): Apns = { notification = None }

///Extends and overrides generic values when delivering via GCM/FCM. [See examples](https://www.ably.io/documentation/general/push/publish#payload-structure)
type Fcm =
    { notification: Option<Notification> }
    ///Creates an instance of Fcm with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (): Fcm = { notification = None }

///Extends and overrides generic values when delivering via web. [See examples](https://www.ably.io/documentation/general/push/publish#payload-structure)
type Web =
    { notification: Option<Notification> }
    ///Creates an instance of Web with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (): Web = { notification = None }

type Push =
    { ///Extends and overrides generic values when delivering via APNs. [See examples](https://www.ably.io/documentation/general/push/publish#payload-structure)
      apns: Option<Apns>
      ///Arbitrary [key-value string-to-string payload](https://www.ably.io/documentation/general/push/publish#channel-broadcast-example).
      data: Option<string>
      ///Extends and overrides generic values when delivering via GCM/FCM. [See examples](https://www.ably.io/documentation/general/push/publish#payload-structure)
      fcm: Option<Fcm>
      notification: Option<Notification>
      ///Extends and overrides generic values when delivering via web. [See examples](https://www.ably.io/documentation/general/push/publish#payload-structure)
      web: Option<Web> }
    ///Creates an instance of Push with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (): Push =
        { apns = None
          data = None
          fcm = None
          notification = None
          web = None }

[<Fable.Core.StringEnum; RequireQualifiedAccess>]
type TransportType =
    | [<CompiledName "apns">] Apns
    | [<CompiledName "fcm">] Fcm
    | [<CompiledName "gcm">] Gcm
    member this.Format() =
        match this with
        | Apns -> "apns"
        | Fcm -> "fcm"
        | Gcm -> "gcm"

///Push recipient details for a device.
type Recipient =
    { ///Client ID of recipient
      clientId: Option<string>
      ///Client ID of recipient
      deviceId: Option<string>
      ///when using APNs, specifies the required device token.
      deviceToken: Option<string>
      ///when using GCM or FCM, specifies the required registration token.
      registrationToken: Option<string>
      ///Defines which push platform is being used.
      transportType: Option<TransportType> }
    ///Creates an instance of Recipient with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (): Recipient =
        { clientId = None
          deviceId = None
          deviceToken = None
          registrationToken = None
          transportType = None }

type SignedTokenRequest =
    { ///The [capabilities](https://www.ably.io/documentation/core-features/authentication#capabilities-explained) (i.e. a set of channel names/namespaces and, for each, a set of operations) which should be a subset of the set of capabilities associated with the key specified in keyName.
      capability: Option<Newtonsoft.Json.Linq.JObject>
      ///The [client ID](https://www.ably.io/documentation/core-features/authentication#identified-clients) to be assosciated with the token. Can be set to * to allow for any client ID to be used.
      clientId: Option<string>
      ///Name of the key used for the TokenRequest. The keyName comprises of the app ID and key ID on an API Key.
      keyName: Option<string>
      ///An unquoted, un-escaped random string of at least 16 characters. Used to ensure the Ably TokenRequest cannot be reused.
      nonce: Option<string>
      ///Time of creation of the Ably TokenRequest.
      timestamp: Option<int>
      ///A signature, generated as an HMAC of each of the above components, using the key secret value.
      mac: Option<string> }
    ///Creates an instance of SignedTokenRequest with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (): SignedTokenRequest =
        { capability = None
          clientId = None
          keyName = None
          nonce = None
          timestamp = None
          mac = None }

type TokenDetails =
    { ///Regular expression representation of the capabilities of the token.
      capability: Option<string>
      ///Timestamp of token expiration.
      expires: Option<int>
      ///Timestamp of token creation.
      issued: Option<int>
      ///Name of the key used to create the token
      keyName: Option<string>
      ///The Ably Token.
      token: Option<string> }
    ///Creates an instance of TokenDetails with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (): TokenDetails =
        { capability = None
          expires = None
          issued = None
          keyName = None
          token = None }

type TokenRequest =
    { ///The [capabilities](https://www.ably.io/documentation/core-features/authentication#capabilities-explained) (i.e. a set of channel names/namespaces and, for each, a set of operations) which should be a subset of the set of capabilities associated with the key specified in keyName.
      capability: Newtonsoft.Json.Linq.JObject
      ///The [client ID](https://www.ably.io/documentation/core-features/authentication#identified-clients) to be assosciated with the token. Can be set to * to allow for any client ID to be used.
      clientId: Option<string>
      ///Name of the key used for the TokenRequest. The keyName comprises of the app ID and key ID on an API Key.
      keyName: string
      ///An unquoted, un-escaped random string of at least 16 characters. Used to ensure the Ably TokenRequest cannot be reused.
      nonce: string
      ///Time of creation of the Ably TokenRequest.
      timestamp: int }
    ///Creates an instance of TokenRequest with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (capability: Newtonsoft.Json.Linq.JObject, keyName: string, nonce: string, timestamp: int): TokenRequest =
        { capability = capability
          clientId = None
          keyName = keyName
          nonce = nonce
          timestamp = timestamp }

[<RequireQualifiedAccess>]
type GetMetadataOfAllChannels =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type GetMetadataOfChannel =
    ///OK
    | OK of payload: ChannelDetails
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type GetMessagesByChannel =
    ///Error
    | DefaultResponse

[<RequireQualifiedAccess>]
type PublishMessagesToChannel =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type GetPresenceOfChannel =
    ///OK
    | OK of payload: list<PresenceMessage>
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type GetPresenceHistoryOfChannel =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type RequestAccessToken =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type DeletePushDeviceDetails =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type GetPushSubscriptionsOnChannels =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type SubscribePushDeviceToChannel =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type GetChannelsWithPushSubscribers =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type UnregisterAllPushDevices =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type GetRegisteredPushDevices =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type RegisterPushDevice =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type UnregisterPushDevice =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type GetPushDeviceDetails =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type PatchPushDeviceDetails =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type PutPushDeviceDetails =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type UpdatePushDeviceDetails =
    ///Error
    | DefaultResponse of payload: Error

type PublishPushNotificationToDevicesPayload =
    { push: Option<Push>
      ///Push recipient details for a device.
      recipient: Recipient }
    ///Creates an instance of PublishPushNotificationToDevicesPayload with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (recipient: Recipient): PublishPushNotificationToDevicesPayload =
        { push = None; recipient = recipient }

[<RequireQualifiedAccess>]
type PublishPushNotificationToDevices =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type GetStats =
    ///Error
    | DefaultResponse of payload: Error

[<RequireQualifiedAccess>]
type GetTime =
    ///Error
    | DefaultResponse of payload: Error
